# Generated by Django 3.2.6 on 2021-08-28 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('start_data', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('due_date', models.DateTimeField(blank=True)),
                ('end_data', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('start_data', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('due_date', models.DateTimeField(blank=True)),
                ('end_data', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=5)),
                ('class_code', models.CharField(max_length=7, unique=True)),
                ('assignments', models.ManyToManyField(blank=True, related_name='assignments', to='classes.Assignments')),
                ('students', models.ManyToManyField(blank=True, related_name='students', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
                ('tests', models.ManyToManyField(blank=True, related_name='tests', to='classes.Tests')),
            ],
        ),
    ]
