# Generated by Django 3.2.6 on 2021-08-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignments',
            new_name='Assignment',
        ),
        migrations.RenameModel(
            old_name='Tests',
            new_name='Test',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='assignments',
        ),
        migrations.AddField(
            model_name='classes',
            name='assignment',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='classes.Assignment'),
        ),
    ]
