# Generated by Django 3.2.6 on 2021-08-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20210828_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='assignment',
            new_name='assignments',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='subject_code',
        ),
        migrations.AddField(
            model_name='classes',
            name='subject',
            field=models.CharField(default='Subject', max_length=20),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_code',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
    ]
