# Generated by Django 3.2.6 on 2021-08-29 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20210829_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
