# Generated by Django 3.2.6 on 2021-08-29 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_rename_teachers_classes_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='end_data',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
