# Generated by Django 3.2.6 on 2021-08-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20210829_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='start_data',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='start_data',
            new_name='start_date',
        ),
    ]
